# Generated by Django 4.2.4 on 2023-09-30 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_new',
        ),
    ]
